// Responsive image props for the heavy content images. The manifest is
// generated by scripts/optimize-images.mjs; images not listed fall through
// unchanged (src only).
import manifest from "./content/image-manifest.json";
import blogManifest from "./content/blog-image-manifest.json";

export function imgProps(src) {
  const m = manifest[src];
  if (!m) return { src };
  const props = { src: m.src, width: m.width, height: m.height };
  if (m.srcSet) {
    props.srcSet = m.srcSet;
    props.sizes = m.sizes;
  }
  return props;
}

// Wide variants for blog and lots-page heroes (scripts/blog-images.mjs).
// `sizes` is per use: the page hero spans up to 1120px, cards far less.

export function heroImgProps(src, sizes) {
  const m = blogManifest[src];
  if (!m) return imgProps(src);
  return { src: m.src, srcSet: m.srcSet, sizes, width: m.width, height: m.height };
}
